### ISSUE TITLE
Can't work with HA2022.4.0

### ISSUE THREAD

**Issue by chongci** [tsunglung/xiaomi_fan_circulator#7]
Could you fix it ? Please @tsunglung 

Logger: homeassistant.setup
Source: setup.py:298
First occurred: 21:46:11 (1 occurrences)
Last logged: 21:46:11

Unable to prepare setup for platform xiaomi_fan_circulator.fan: Platform not found (cannot import name 'SPEED_OFF' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).

**Comment by rootsnet** [comment]
I have the same problem.
I hope the problem to be fixed.

**Comment by chongci** [comment]
@tsunglung Thanks for your update, I have update to latest ver. , but still have following error message

Logger: homeassistant.setup
Source: setup.py:298
First occurred: 19:24:35 (1 occurrences)
Last logged: 19:24:35

Unable to prepare setup for platform xiaomi_fan_circulator.fan: Platform not found (cannot import name 'ATTR_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).

**Comment by chongci** [comment]
@tsunglung it’s no error message now, but it can not to set fan speed percentage with HA or Homekit, thanks!

**Comment by davegg33** [comment]
I have the same issue, after upgraded to latest HA version, I was unable to set fan speed but other functions like Oscillate are working.

**Comment by mong736** [comment]
I have the same issue. I'm running HA2022.8.4.
Only On/Off work. Fan speed is not working.

**Comment by tsunglung** [comment]
This repo was not maintained any more.
The FA1/FB1 support was moved to https://github.com/tsunglung/xiaomi_fan.
